name: Streamlit App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test analysis scripts
      run: |
        cd scripts
        python main.py
        
    - name: Test Streamlit app
      run: |
        # Test that the app can be imported without errors
        python -c "import sys; sys.path.append('.'); import app"
        
    - name: Generate static version
      run: |
        python generate_static.py
        
    - name: Archive analysis outputs
      uses: actions/upload-artifact@v4
      with:
        name: analysis-outputs
        path: |
          outputs/
          docs/
