name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test data imports
      run: |
        python -c "from scripts.players_data import players, points_system; print(f'✅ Loaded {len(players)} players')"
        python -c "from scripts.analysis import calculate_player_score; print('✅ Analysis functions loaded')"
        
    - name: Test analysis pipeline
      run: |
        python scripts/main.py
        ls -la outputs/
        
    - name: Test Streamlit app
      run: |
        python -c "import sys; sys.path.append('.'); import app; print('✅ Streamlit app imports successfully')"
        
    - name: Test static site generation
      run: |
        python generate_static.py
        ls -la docs/
        
    - name: Archive test outputs
      uses: actions/upload-artifact@v4
      with:
        name: test-outputs
        path: |
          outputs/
          docs/
        retention-days: 7
