name: Streamlit App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test analysis scripts
      run: |
        # Test that data files can be imported
        python -c "from scripts.players_data import players, points_system; print(f'✅ Loaded {len(players)} players')"
        python -c "from scripts.analysis import calculate_player_score; print('✅ Analysis functions loaded')"
        
        # Run the main analysis pipeline
        python scripts/main.py
        
    - name: Test Streamlit app
      run: |
        # Test that the app can be imported without errors
        python -c "import sys; sys.path.append('.'); import app; print('✅ Streamlit app imports successfully')"
        
    - name: Generate static version
      run: |
        python generate_static.py
        
    - name: Archive analysis outputs
      uses: actions/upload-artifact@v4
      with:
        name: analysis-outputs
        path: |
          outputs/
          docs/
